### PR TITLE
Fixed free issue at startup

### PR DESCRIPTION
**Pull request by MrHug**
Hi guys,

I took an interest in your project and fixed a start-up issue I encountered. It seemed to be a double free issue, that has been solved by initializing some variables to 0.

Gr. MrHug

### CODE REVIEW

**Comment by MrHug** [comment]
Sorry guys, I'll come up with a more substantial (and better organized) pull request soon for level creation.

**Comment by leonn** [comment]
Thank you. We appreciate your interest in our project, I see you've noticed some errors that we have not given proper attention, nice look.

Soon we will  work on improvements to a release version and move the team work to a private repository on gitbucket, so we can work on a comercial version to (Linux , Windows, PS3 & Xbox) and future versions for IOS & android.

So if your  interest in our project  raise to the point of working with us, be in touch.

Leonn Paiva.

**Comment by MrHug** [comment]
Ah that's a pity... I must say I do like your project and I think that I could have some things to contribute, the problem is that I have very little time. So my contributions would be sparse and without definite predictions on when they will be done, which is why a git fork works so well for me :)

Regardless I would like to keep on working with you, the problem is how and when...

**Comment by leonn** [comment]
No problem our team is kinda little, so any  contribuition is welcome, no matter when. thanks.

**Pull request closed without merging**
